In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Array a:", a)
print("Array b:", b)
print("\n--- Array Math ---")
print("Addition:       ", a + b)
print("Subtraction:    ", a - b)
print("Multiplication: ", a * b)
print("Division:       ", a / b)
print("Power (a2):   ", a ** 2)
print("Modulo (b % a): ", b % a)
print("Square root (a):", np.sqrt(a))
print("Sum of a:       ", np.sum(a))
print("Mean of b:      ", np.mean(b))
print("Max of a:       ", np.max(a))
print("Min of b:       ", np.min(b))
print("Dot product:    ", np.dot(a, b))


Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

--- Array Math ---
Addition:        [11 22 33 44 55]
Subtraction:     [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:        [0.1 0.1 0.1 0.1 0.1]
Power (a2):    [ 1  4  9 16 25]
Modulo (b % a):  [0 0 0 0 0]
Square root (a): [1.         1.41421356 1.73205081 2.         2.23606798]
Sum of a:        15
Mean of b:       30.0
Max of a:        5
Min of b:        10
Dot product:     550


In [2]:
# Create two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Addition
print("\nA + B:")
print(A + B)

# Subtraction
print("\nA - B:")
print(A - B)



Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B:
[[ 6  8]
 [10 12]]

A - B:
[[-4 -4]
 [-4 -4]]


In [3]:
# Element-wise multiplication
print("\nA * B (element-wise):")
print(A * B)

# Matrix multiplication
print("\nA @ B (matrix multiplication):")
print(A @ B)

# Division (element-wise)
print("\nA / B:")
print(A / B)

# Transpose
print("\nTranspose of A:")
print(A.T)

# Determinant of A
print("\nDeterminant of A:")
print(np.linalg.det(A))


A * B (element-wise):
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

A / B:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004


In [4]:
ab = np.zeros((2, 3))
print(ab)
ba = np.ones((2, 3))
print(ba)
ac = np.arange(1, 11, 2)
print(ac)
bc=ac.reshape(1,5)
print(bc)
print(bc.flatten())
ad = np.eye(3)
print(ad)
e = np.linspace(0, 10, 5)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[1 3 5 7 9]]
[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.   2.5  5.   7.5 10. ]


In [7]:
f = np.random.rand(3,2)
print(f)

g = np.random.randn(2, 3)
print(g)

[[0.46794489 0.05589733]
 [0.84197215 0.14249625]
 [0.52650005 0.80599412]]
[[ 0.46797137 -0.80394982  0.74586747]
 [ 1.08114176 -1.13217413 -0.85653852]]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
d=np.hstack((a,b))
print(c,"" ,d)

[[1 2 3]
 [4 5 6]]  [1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

c = np.concatenate((a, b), axis=0)
print(c)

In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)
a+5

[[11 22 33]
 [14 25 36]]


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a = np.array([1, 2, 3, 4])

np.save("data.npy", a)
loaded = np.load("data.npy")
print(loaded)

[1 2 3 4]
